server:
  port: 1000
sdwan:
  controller:
    port: 18848
    cidr: 10.1.0.0/20
    staticNodes:
      - id: test1
        hardwareAddress: fa:50:03:01:f8:00
        vip: 10.1.0.5
      - id: test2
        hardwareAddress: fa:2e:16:1b:26:00
        vip: 10.1.0.6