server:
  port: 8080
sdwan:
  controller:
    port: 8085
    cidr: 10.1.0.0/20
    # second
    sdArpTTL: 300
#    staticNodes:
#      - id: 192.222.0.66
#        macAddress: fa:50:03:01:f8:00
#        vip: 10.1.0.66
#      - id: 192.222.0.69
#        macAddress: fa:2e:16:1b:26:00
#        vip: 10.1.0.69
#      - id: 172.168.1.26
#        macAddress: fc:34:97:e3:b5:64
#        vip: 10.1.0.26
#    staticRoutes:
#      - id: route-192.222.8.159
#        destination: 192.222.8.159/32
#        nextHop: 10.1.0.69
#      - id: route-192.168.1.0/24
#        destination: 192.168.1.0/24
#        nextHop: 10.1.0.69