create table static_node
(
    id          bigint       NOT NULL generated by default as identity,
    vip         varchar(128) NOT NULL,
    mac_address varchar(32)  NOT NULL,
    remark      varchar(128),
    constraint static_node_id_key PRIMARY KEY (id)
);

create unique index static_node_vip_uindex
    on static_node (vip);

create unique index static_node_mac_uindex
    on static_node (mac_address);

create table static_route
(
    id          bigint       NOT NULL generated by default as identity,
    destination varchar(128) NOT NULL,
    mesh_id     bigint       NOT NULL,
    remark      varchar(128),
    constraint static_route_id_key PRIMARY KEY (id)
);