sdwan:
  node:
    tun:
      mtu: 1400
    controller:
      address: 127.0.0.1:8081
      connectTimeout: 30000
      callTimeout: 3000
    stun:
      address: stun.miwifi.com:3478
      callTimeout: 3000
      mappingTimeout: 3000
      heartTimeout: 300
    relay:
      address: 127.0.0.1:8082
      heartTimeout: 300
