server:
  port: 1001
sdwan:
  node:
    # connect
    controllerHost: 127.0.0.1
    controllerPort: 8085
    connectTimeout: 30000
    mtu: 1400
    # address
    stunServer: stun.miwifi.com:3478
    localIP: 127.0.0.1
