server:
  port: 1001
sdwan:
  node:
    # connect
    controllerHost: 127.0.0.1
    controllerPort: 18848
    connectTimeout: 30000
    mtu: 1400
    # address
    addressType: static
    localIP: 192.222.0.66
    staticIP: 127.0.0.1
    staticPort: 888
    # node
    nodeType: mesh
    routes:
      - 192.222.0.8/32