server:
  port: 1001
sdwan:
  node:
    # connect
    controllerHost: 192.222.0.66
    controllerPort: 18848
    connectTimeout: 30000
    mtu: 1400
    # node
    nodeType: mesh
    # address
    localIP: 192.222.0.69
