server:
  port: 1001
sdwan:
  node:
    # connect
    controllerHost: 192.222.0.66
    controllerPort: 18848
    connectTimeout: 30000
    mtu: 1400
    # address
    addressType: static
    localIP: 192.222.0.66
    staticIP: 192.222.0.66
    staticPort: 888
    # node
    nodeType: simple
    routes:
      - 192.222.0.67/32